name       : slurp
version    : 1.4.0
release    : 2
source     :
    - https://github.com/emersion/slurp/archive/refs/tags/v1.4.0.tar.gz : a332bd40168eb73361ea811eae01d6d1210f9eadb0a486e2dd7a03efb81a3772
license    : MIT
component  : multimedia.graphics
summary    : Select a region in a Wayland compositor and print it to the standard output.
description: |
    Select a region in a Wayland compositor and print it to the standard output.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
