name       : slurp
version    : 1.3.2
release    : 1
source     :
    - https://github.com/emersion/slurp/archive/refs/tags/v1.3.2.tar.gz : 005dd8601d4bada9728f434728c7a57c955f90f9b9f53d1ffb051abdbabb9876
license    : MIT
component  : multimedia.graphics
summary    : Select a region in a Wayland compositor and print it to the standard output.
description: |
    Select a region in a Wayland compositor and print it to the standard output.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
